ops: update action

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -85,24 +85,24 @@ jobs:
       #     echo "System Logs Related to WireGuard:"
       #     sudo journalctl -xe | grep -i wireguard
 
+      # - name: Test Registry Connection
+      #   run: |
+      #     echo "Testing connection to registry..."
+      #     curl -v --max-time 10 http://${{ secrets.REGISTRY_HOST }}:30000/v2/ || echo "Curl failed, but continuing workflow"
+
+      # - name: Network diagnostics
+      #   run: |
+      #     echo "Pinging registry host..."
+      #     ping -c 4 ${{ secrets.REGISTRY_HOST }}
+      #     echo "Tracing route to registry host..."
+      #     traceroute ${{ secrets.REGISTRY_HOST }}
+      #     echo "Checking registry connection..."
+      #     nc -zv ${{ secrets.REGISTRY_HOST }} 30000
+
       - name: Configure Dockerregistry
         run: |
           echo '{ "insecure-registries" : ["${{ secrets.REGISTRY_HOST }}:30000"] }' | sudo tee /etc/docker/daemon.json
           sudo systemctl restart docker
-
-      - name: Test Registry Connection
-        run: |
-          echo "Testing connection to registry..."
-          curl -v --max-time 10 http://${{ secrets.REGISTRY_HOST }}:30000/v2/ || echo "Curl failed, but continuing workflow"
-
-      - name: Network diagnostics
-        run: |
-          echo "Pinging registry host..."
-          ping -c 4 ${{ secrets.REGISTRY_HOST }}
-          echo "Tracing route to registry host..."
-          traceroute ${{ secrets.REGISTRY_HOST }}
-          echo "Checking registry connection..."
-          nc -zv ${{ secrets.REGISTRY_HOST }} 30000
 
       - name: Build Docker image
         run: |
